// === server.js ===
// Run this file with: node server.js
const express = require("express");
const http = require("http");
const socketIO = require("socket.io");

const app = express();
const server = http.createServer(app);
const io = socketIO(server);

app.use(express.static("public")); // Serve frontend from 'public' folder

// Object to hold rooms and their participants' checkbox states
let rooms = {
  "Room 1": ["Alice", "Bob", "Charlie"],
  "Room 2": ["Diana", "Eve", "Frank"],
  // Add more rooms as needed
};

io.on("connection", (socket) => {
  console.log("A user connected:", socket.id);

  // When a user joins a room
  socket.on("joinRoom", (roomName) => {
    socket.join(roomName);
    console.log(`${socket.id} joined ${roomName}`);

    // Send current room's checkbox state to the user
    socket.emit("initialState", rooms[roomName]);

    // Listen for checkbox changes
    socket.on("checkboxChange", ({ roomName, name, checked }) => {
      // Update the room's checkbox state
      const room = rooms[roomName];
      if (room) {
        const index = room.findIndex((person) => person === name);
        if (index !== -1) {
          room[index].checked = checked;
        }
      }
      // Broadcast to other users in the same room
      socket.to(roomName).emit("checkboxUpdate", { name, checked });
    });
  });

  // Disconnect
  socket.on("disconnect", () => {
    console.log("User disconnected:", socket.id);
  });
});

server.listen(3000, () => {
  console.log("Server is running on http://localhost:3000");
});
